#!/usr/bin/env bash

set -euo pipefail

snakemake \
    --use-conda \
    --profile profile/default \
    --jobs 100 \
    --cores 24 \
    --keep-going \
    --latency-wait 60 \
    --cache \
        preprocess__recompress__host__ \
        preprocess__recompress__mags__ \
        helpers__samtools__index_fa_gz__ \
        preprocess__index__ \
        quantify__index__ \
    --groups \
        preprocess__fastp__="run_{sample_id}" \
        preprocess__fastp__import__="run_{sample_id}" \
        preprocess__bowtie2__cram_to_fastq__="run_{sample_id}" \
        preprocess__bowtie2__="run_{sample_id}" \
        quantify__bowtie2__cram_to_fastq__="run_{sample_id}" \
        quantify__bowtie2__="run_{sample_id}" \
    "$@"
